Repository Kajol-Kumari/InfluMart, pull requests merged in 2024-07, with the labels that each got.

#162 Highlight Mandatory fields and Add avatar images
  frontend/assets/influencer1.jpg
  frontend/assets/influencer10.jpg
  frontend/assets/influencer2.jpg
  frontend/assets/influencer3.jpg
  frontend/assets/influencer4.jpg
  frontend/assets/influencer5.jpg
  frontend/assets/influencer6.jpg
  frontend/assets/influencer7.jpg
  frontend/assets/influencer8.jpg
  frontend/assets/influencer9.jpg
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/screens/signup/SignUpStyles.scss.js
Labels: gssoc, level1, frontend

#158 [Frontend] Integrating payment interface with the app
  frontend/.env.sample
  frontend/.gitignore
  frontend/controller/paymentController.js
  frontend/netlify/functions/netlify.toml
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/util/paymentFuntions.js
Labels: gssoc, level3

#164 [Backend] Making payment interface flow dynamic with user prefill content data Fixed
  frontend/controller/paymentController.js
  frontend/controller/subscriptionController.js
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/shared/PlansBox.jsx
  frontend/util/paymentFuntions.js
Labels: gssoc, level3

#165 [frontend] add a login alert for not logged in user in marketplace and show avtar for those if no dp is there for brand or Influencer Fixed
  frontend/components/Depth1Frame17.js
  frontend/components/Depth1Frame9.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Influencer/Settings/Support/InfluencerContactUs.js
  frontend/screens/InfluencerList/IncluencerCard.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/UserProfile/UserProfile.js
  frontend/util/ImageWithFallback.js
Labels: gssoc, level2

#168 account-verification-integration
  backend/config/configs.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  frontend/app.json
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Influencer/components/AddHandles.js
Labels: DO NOT MERGE

#169 [Backend] adding a field of name for brand and name , mobile no store and category for influencer in their respective db models without disturbing other functionalities Added
  backend/.env.sample
  backend/config/configs.js
  backend/model/brandDbRequestModel.js
  backend/model/influencerSignupRequestModel.js
  backend/utils/encryption.js
Labels: gssoc, level3

#171 Integrate new signup form changes with backend and merge conflict issue Fixed
  backend/controllers/brandController.js
  backend/controllers/influencerController.js
  frontend/controller/signupController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/shared/DropDown.jsx
Labels: gssoc, level2

#173 [frontend]updating influencer profile , influencer list , brand profle , brand list with names instaed of usernames Fixed
  backend/controllers/brandController.js
  backend/controllers/influencerController.js
  frontend/components/Depth1Frame17.js
  frontend/components/Depth1Frame9.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/UserProfile/UserProfile.js
  frontend/screens/signup/BrandRegistrationForm.js
Labels: gssoc, level2

#175 Creating Filtering and searching functionality for list of influencers Added
  backend/controllers/influencerController.js
  backend/routes/influencerRoutes.js
  backend/utils/influencerAnalytics.js
Labels: gssoc, level3

#177 Forget&Reset Password Functionality for Brand and Influencers Added
  backend/.env.sample
  backend/config/configs.js
  backend/controllers/passwordController.js
  backend/model/influencerSignupRequestModel.js
  frontend/App.js
  frontend/controller/PasswordController.js
  frontend/screens/login/ForgotPasswordPage.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/login/ResetPasswordPage.js
Labels: gssoc, level3

#182 [Backend] A messaging platform between brands and influencers to connect Added
  backend/controllers/connectController.js
  backend/index.js
  backend/model/Message.js
  backend/package-lock.json
  backend/package.json
  backend/routes/connectionRoutes.js
Labels: gssoc, level3

#183 Filter page ui fixed
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/FiltersUI.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/shared/CustomSlider.jsx
  frontend/shared/DropDown.jsx
Labels: gssoc, level3

#187 [frontend] After verification of Youtube account, it's not able to redirect to the app Fixed
  backend/.env.sample
  backend/index.js
  backend/routes/authRoutes.js
  frontend/.env.sample
  frontend/App.js
  frontend/screens/Influencer/components/AddHandles.js
Labels: gssoc, level3

#188 making inbox and chat interface ui interactive and refactoring fixed
  frontend/screens/BrandProfile.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/chat/ChatStyles.scss.js
  frontend/screens/chat/components/MessageInput.js
  frontend/screens/inbox/InboxInterface.js
  frontend/screens/inbox/InboxInterface.scss.js
Labels: gssoc, level3

#191 Fixing UI components
  frontend/assets/back_arrow_light.png
  frontend/assets/search_light.png
  frontend/components/Depth1Frame.js
  frontend/components/Depth1Frame11.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/components/MaxFollowers.scss.js
  frontend/screens/Influencer/components/MaxFollowersNo.js
  frontend/screens/InfluencerList/IncluencerCard.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/signup/BrandRegistrationForm.js
Labels: gssoc, level2

#194 BrandList UI Fixed
  frontend/screens/BrandsAssosciated.js
Labels: gssoc, level2

#193 integrate messaging backend with frontend. Fixed
  backend/controllers/connectController.js
  backend/controllers/influencerController.js
  backend/index.js
  backend/middleware/brandorInfluencerAuthenticationMiddleware.js
  backend/model/Message.js
  backend/model/brandDbRequestModel.js
  backend/model/conversation.js
  backend/model/influencerSignupRequestModel.js
  backend/routes/connectionRoutes.js
  backend/socket/socket.js
  frontend/App.js
  frontend/controller/connectionsController.js
  frontend/controller/loginController.js
  frontend/helpers/socket.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/FriendRequestPage.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/chat/components/MessageInput.js
  frontend/screens/inbox/InboxInterface.js
  frontend/util/SocketContext.js
Labels: gssoc, level3

#204 [bug] fixing signup issue and login issue Fixed
  backend/controllers/brandController.js
  backend/controllers/connectController.js
  backend/controllers/influencerController.js
  backend/middleware/brandorInfluencerAuthenticationMiddleware.js
  backend/utils/influencerAnalytics.js
  frontend/controller/brandController.js
  frontend/controller/loginController.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/InfluencerList/InfluencersList.js
Labels: gssoc, level3

#206 integrate ui filter with backend added
  backend/controllers/influencerController.js
  frontend/controller/InfluencerController.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/FiltersUI.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/shared/CustomSlider.jsx
Labels: gssoc, level3

#211 [bug] influencer registration form bugs fixed
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/PlanChooseInterface.js
Labels: gssoc, backend, level2

#210 Message inbox and chat interface ui fixed
  frontend/assets/plus_icon.png
  frontend/assets/search_icon.png
  frontend/assets/send_icon.png
  frontend/controller/connectionsController.js
  frontend/helpers/GraphData.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/chat/ChatStyles.scss.js
  frontend/screens/chat/components/MessageInput.js
  frontend/screens/inbox/InboxInterface.js
  frontend/screens/inbox/InboxInterface.scss.js
Labels: gssoc, level3

#212 [bug] messaging platform bugs fixed
  backend/controllers/connectController.js
  frontend/controller/connectionsController.js
Labels: gssoc, level2

#215 [backend] create collab post api added
  backend/controllers/CollabOpenController.js
  backend/index.js
  backend/model/CollabOpening.js
  backend/routes/collabOpenRoutes.js
Labels: gssoc, level3, backend

#216 Loader added to show the operation/API Call
  frontend/screens/Analytics/Analytics.js
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/FiltersUI.js
  frontend/screens/FriendRequestPage.js
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/screens/Influencer/Settings/Support/InfluencerDeleteAccount.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/OtpVerification.js
  frontend/screens/UserProfile/UserProfile.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/inbox/InboxInterface.js
  frontend/screens/login/ForgotPasswordPage.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/login/ResetPasswordPage.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/shared/Loader.jsx
Labels: gssoc, level2

#217 [backend]create a api to get list of all collab posted by brands added
  backend/controllers/CollabOpenController.js
  backend/routes/collabOpenRoutes.js
Labels: gssoc, level2

#219 [backend]making connect request api added
  backend/controllers/CollabOpenController.js
  backend/model/CollabOpenRequest.js
  backend/model/brandDbRequestModel.js
  backend/routes/collabOpenRoutes.js
Labels: gssoc, level3

#222 new ui fixes fixed
  frontend/App.js
  frontend/assets/collab/depth-4-frame-0.png
  frontend/assets/collab/depth-4-frame-01.png
  frontend/assets/collab/depth-5-frame-0.png
  frontend/assets/collab/depth-5-frame-01.png
  frontend/screens/collabOpen/CampaignDetail.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#226 Influencer signUp flow fix for mobile app fixed
  frontend/controller/paymentController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandProfile.scss.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/signup/SignUpStyles.scss.js
  frontend/util/SocketContext.js
  frontend/util/paymentFuntions.js
Labels: gssoc, level3

#221 AboutUS, ContactUs and Service Page Added
  frontend/App.js
  frontend/assets/Influmart.png
  frontend/assets/about us.png
  frontend/assets/contact us.png
  frontend/assets/home-page-cover.png
  frontend/components/Depth1Frame3.js
  frontend/screens/AboutUs.js
  frontend/screens/BrandService.js
  frontend/screens/Homepage.js
  frontend/screens/Influencer/Settings/Support/InfluencerContactUs.js
  frontend/screens/Influencer/Settings/Support/InfluencerContactUs.scss.js
  frontend/screens/InfluencerService.js
Labels: gssoc, level3

#231 integrate collab backend apis with ui complete all pages fixed
  backend/model/CollabOpening.js
  backend/routes/collabOpenRoutes.js
  frontend/components/BrandProfileBottomBar.js
  frontend/controller/collabOpenController.js
  frontend/screens/BrandProfile.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#245 [BUG] Influencer signup error fixed
  backend/controllers/influencerController.js
  backend/model/influencerSignupRequestModel.js
Labels: gssoc, level2

#228 Issue : 227 - UI changes | Frontend
  frontend/assets/network_icon_light.png
  frontend/assets/network_light_icon.png
  frontend/assets/notification_icon_light.png
  frontend/assets/post_icon.png
  frontend/components/BrandProfileBottomBar.js
  frontend/components/Depth1Frame13.js
  frontend/screens/collabOpen/CampaignDetail.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#247 Homepage Changed
  frontend/GlobalStyles.js
  frontend/assets/feature2.png
  frontend/assets/feature3.jpg
  frontend/assets/feature4.jpg
  frontend/assets/feature5.jpg
  frontend/assets/feature6.jpg
  frontend/assets/feature7.jpg
  frontend/assets/feature8.jpg
  frontend/assets/feature9.jpg
  frontend/assets/home-page-cover.png
  frontend/components/Depth1Frame4.js
  frontend/controller/homeController.js
  frontend/screens/BrandProfile.scss.js
  frontend/screens/FiltersUI.js
  frontend/screens/Homepage.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/collabOpen/CollabForm.js
Labels: gssoc, level3

#249 integration of request api for collab posts between brands and influencer Added
  backend/model/brandDbRequestModel.js
  frontend/controller/collabOpenController.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandProfile.scss.js
  frontend/screens/collabOpen/CampaignDetail.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#251 Brand Collab request and accept,reject Ui And refactor Fixed
  frontend/App.js
  frontend/controller/brandController.js
  frontend/controller/collabOpenController.js
  frontend/controller/collabrationController.js
  frontend/controller/homeController.js
  frontend/controller/loginController.js
  frontend/screens/BrandProfile/BrandProfile.js
  frontend/screens/BrandProfile/BrandProfile.scss.js
  frontend/screens/BrandProfile/components/BrandCollabRequestPage.js
  frontend/screens/BrandProfile/components/BrandProductCard.js
  frontend/screens/inbox/InboxInterface.js
Labels: gssoc, level3

#255 New feature image and callender added
  backend/controllers/CollabOpenController.js
  backend/model/CollabOpening.js
  backend/routes/collabOpenRoutes.js
  backend/uploads/brandCollabPhoto/dummy.txt
  frontend/controller/collabOpenController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/collabOpen/CampaignDetail.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#256 UI Fixed
  frontend/assets/green_tick.png
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/Influencer/components/MaxFollowersNo.js
  frontend/screens/Influencer/components/PricePerPost.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/shared/PlansBox.jsx
Labels: gssoc, level3

#261 adding payment system when brands submit post collab form in their profile Added
  frontend/App.js
  frontend/controller/collabOpenController.js
  frontend/controller/paymentController.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/collabOpen/CollabOpenPayment.js
  frontend/screens/collabOpen/CollabOpenPayment.scss.js
  frontend/screens/collabOpen/CollabPost.js
Labels: gssoc, level3

#264 [BUG] In mobile app fixed
  frontend/screens/BrandsAssosciated.js
Labels: gssoc, level2

#267 Backend : Collabration Request and Collab Open Request were Fixed
  backend/controllers/CollabOpenController.js
  backend/controllers/connectController.js
  frontend/controller/collabOpenController.js
  frontend/controller/connectionsController.js
Labels: gssoc, level3

#274 Minor bug fix
  frontend/components/Depth1Frame11.js
Labels: gssoc, level1

#279 [bug] if after successful payment account is not created then auto refund should happen Fixed
  backend/controllers/influencerController.js
  backend/controllers/paymentController.js
  backend/controllers/subscriptionController.js
  frontend/controller/signupController.js
  frontend/controller/subscriptionController.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/collabOpen/CollabOpenPayment.js
Labels: gssoc, level3

#282 [Bug] Multiple Issues to fix is Fixed
  backend/model/influencerSignupRequestModel.js
  frontend/.env.sample
  frontend/components/Depth1Frame4.js
  frontend/screens/Homepage.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/signup/components/HeadingDescToggle.jsx
  frontend/shared/DropDown.jsx
  frontend/shared/PlaceSearchBar.jsx
Labels: gssoc, level3

#286 Avatar added in influencer registartion
  frontend/assets/avatars/avatar1.png
  frontend/assets/avatars/avatar10.png
  frontend/assets/avatars/avatar11.png
  frontend/assets/avatars/avatar12.png
  frontend/assets/avatars/avatar13.png
  frontend/assets/avatars/avatar14.png
  frontend/assets/avatars/avatar15.png
  frontend/assets/avatars/avatar16.png
  frontend/assets/avatars/avatar17.png
  frontend/assets/avatars/avatar18.png
  frontend/assets/avatars/avatar19.png
  frontend/assets/avatars/avatar2.png
  frontend/assets/avatars/avatar20.png
  frontend/assets/avatars/avatar21.png
  frontend/assets/avatars/avatar22.png
  frontend/assets/avatars/avatar23.png
  frontend/assets/avatars/avatar24.png
  frontend/assets/avatars/avatar25.png
  frontend/assets/avatars/avatar26.png
  frontend/assets/avatars/avatar27.png
  frontend/assets/avatars/avatar28.png
  frontend/assets/avatars/avatar3.png
  frontend/assets/avatars/avatar4.png
  frontend/assets/avatars/avatar5.png
  frontend/assets/avatars/avatar6.png
  frontend/assets/avatars/avatar7.png
  frontend/assets/avatars/avatar8.png
  frontend/assets/avatars/avatar9.png
  frontend/components/Depth1Frame13.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/Influencer/components/UserProfilePhoto.scss.js
  frontend/screens/InfluencerList/IncluencerCard.js
Labels: gssoc, level3

#288 FAQ Page fixed
  frontend/screens/Influencer/Settings/Support/InfluencerHelpCenter.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
Labels: gssoc, level2

#289 Currency dynamic Added
  backend/controllers/influencerController.js
  backend/controllers/paymentController.js
  frontend/constants/countries.js
  frontend/controller/paymentController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Influencer/components/PricePerPost.js
  frontend/screens/collabOpen/CollabOpenPayment.js
  frontend/shared/CountryCurrencyPicker.jsx
Labels: gssoc, level3

#294 profile photo issue Fixed
  backend/controllers/CollabOpenController.js
  backend/controllers/connectController.js
  backend/controllers/influencerController.js
  backend/model/influencerSignupRequestModel.js
  frontend/components/Depth1Frame17.js
  frontend/components/Depth1Frame9.js
  frontend/controller/InfluencerController.js
  frontend/controller/collabOpenController.js
  frontend/controller/signupController.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/InfluencerList/IncluencerCard.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/UserProfile/UserProfile.js
  frontend/util/ImageWithFallback.js
Labels: gssoc, level3

#292 UI and minor issues fixed
  frontend/screens/Homepage.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/shared/DropDown.jsx
  frontend/shared/MultiDropDown.jsx
Labels: gssoc, level3

#300 [Bug] profile photo of brand Fixed
  backend/controllers/brandController.js
  backend/controllers/connectController.js
  backend/model/brandDbRequestModel.js
  frontend/constants/Avatars.js
  frontend/controller/InfluencerController.js
  frontend/controller/brandController.js
  frontend/controller/collabOpenController.js
  frontend/controller/connectionsController.js
  frontend/controller/homeController.js
  frontend/controller/signupController.js
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/BrandAccountSignupDataPreview.scss.js
  frontend/screens/BrandProfile/BrandProfile.js
  frontend/screens/BrandProfile/components/BrandProductCard.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Homepage.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/UserProfile/ProductCard.js
  frontend/screens/UserProfile/UserProfile.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/chat/components/MessageInput.js
  frontend/screens/collabOpen/CampaignDetail.js
  frontend/screens/inbox/InboxInterface.js
Labels: gssoc, level3

#301 UI Hiccups Fixed
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/collabOpen/CollabForm.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/screens/signup/components/HeadingDescToggle.jsx
  frontend/shared/DropDown.jsx
  frontend/shared/MultiDropDown.jsx
  frontend/shared/PlaceSearchBar.jsx
Labels: gssoc, level2
