Repository Kajol-Kumari/InfluMart, pull requests merged in 2024-06, with the labels that each got.

#8 [Backend] API to Get the influencers data form their Social Handles added
  backend/config/dbConfig.js
  backend/controllers/influencerController.js
  backend/index.js
  backend/middleware/influencers/influencerAuthorizationMiddleware.js
  backend/middleware/influencers/influencerLoggingMiddleware.js
  backend/model/influencerSignupRequestModel.js
  backend/model/influencers.js
  backend/package-lock.json
  backend/package.json
  backend/routes/influencerRoutes.js
  backend/utils/influencerAnalytics.js
Labels: gssoc, level3

#12 [Backend] Create Subscription
  backend/config/dbConfig.js
  backend/controllers/subscriptionController.js
  backend/index.js
  backend/model/Subscription.js
  backend/routes/subscriptionRouter.js
Labels: gssoc, level3

#16 [Backend] Sending Otp and verification of otp via email for brands added
  backend/.env.sample
  backend/config/dbConfig.js
  backend/constant/constants.js
  backend/controllers/otpController.js
  backend/index.js
  backend/model/otp.js
  backend/package-lock.json
  backend/package.json
  backend/routes/otpRoutes.js
Labels: gssoc, level3

#14 [Backend] Get Subscription Charges API Added
  backend/controllers/subscriptionController.js
  backend/routes/subscriptionRouter.js
Labels: gssoc, level3

#17 [Backend] integrating databse to backend for brands
  backend/controllers/brandController.js
  backend/index.js
  backend/middleware/brands/brandAuthenticationMiddleware.js
  backend/middleware/brands/validations/brandSignUpValidate.js
  backend/model/brandDbRequestModel.js
  backend/routes/brandRoutes.js
Labels: gssoc, level3

#19 [Discussion] A way Brands can talk to influencers Completed
  backend/messagingService/README.md
Labels: gssoc, level1

#18 [Frontend] Integration the Brand Signup with Backend Fixed
  backend/constant/constants.js
  backend/controllers/otpController.js
  frontend/.env.sample
  frontend/App.js
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/BrandRegistrationForm.js
  frontend/screens/OtpVerification.js
Labels: gssoc, level2

#33 Login pages integrated with backend
  frontend/App.js
  frontend/babel.config.js
  frontend/controller/loginController.js
  frontend/screens/LoginPage.js
  frontend/screens/LoginPageBrands.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/login/LoginStyle.js
Labels: gssoc, level3

#35 [Frontend] Brand SignUp UI Enhancement Completed
  frontend/App.js
  frontend/assets/multiselect/check.png
  frontend/assets/multiselect/chevron.png
  frontend/assets/multiselect/close.png
  frontend/assets/multiselect/search.png
  frontend/controller/signupController.js
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/BrandRegistrationForm.js
  frontend/screens/OtpVerification.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/screens/signup/SignUpStyles.scss.js
  frontend/shared/MultiSelect.jsx
Labels: gssoc, level2

#38 [Frontend] Making inbox interface responsive. #36
  frontend/App.js
  frontend/screens/InboxInterface.js
  frontend/screens/chat/ChatInterface.js
  frontend/screens/chat/ChatStyles.scss.js
  frontend/screens/inbox/InboxInterface.js
  frontend/screens/inbox/InboxInterface.scss.js
Labels: gssoc, level1

#43 [Backend] Otp Verification issue with Login Brand Fixed
  backend/controllers/brandController.js
  frontend/controller/loginController.js
  frontend/controller/signupController.js
  frontend/package-lock.json
  frontend/package.json
Labels: gssoc, level2

#45 [Bug] The Brand Login and Signup Not as expected Fixed
  backend/controllers/brandController.js
Labels: gssoc, level1

#60 [Frontend] Integrate the analytics Graph on Influencers Profile Added
  backend/.env.sample
  backend/config/dbConfig.js
  backend/controllers/influencerController.js
  backend/utils/influencerAnalytics.js
  frontend/App.js
  frontend/controller/socialController.js
  frontend/helpers/GraphData.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Analytics.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/Analytics/Analytics.scss.js
  frontend/screens/Analytics/components/Images/AllImages.js
  frontend/screens/Analytics/components/Images/images.scss.js
  frontend/screens/Analytics/components/MyGraphs/AllGraphs.js
  frontend/screens/Analytics/components/MyGraphs/graphs.scss.js
  frontend/screens/Analytics/components/stats/AllStats.js
  frontend/screens/Analytics/components/stats/stats.scss.js
  frontend/shared/MyLineChart.jsx
Labels: gssoc, level3, backend, frontend

#71 [Frontend] Integration the Influencers Signup with Backend Fixed
  backend/controllers/influencerController.js
  backend/controllers/subscriptionController.js
  backend/index.js
  backend/model/Subscription.js
  backend/model/influencerSignupRequestModel.js
  backend/routes/influencerRoutes.js
  backend/utils/influencerAnalytics.js
  frontend/App.js
  frontend/assets/camera_symbol.png
  frontend/assets/coin_symbol.png
  frontend/assets/cross_symbol.png
  frontend/assets/currency_symbol.png
  frontend/assets/face_symbol.png
  frontend/assets/instagram_symbol.png
  frontend/assets/sun_symbol.png
  frontend/assets/tt_symbol.png
  frontend/assets/verify_symbol.png
  frontend/assets/yt_symbol.png
  frontend/controller/loginController.js
  frontend/controller/signupController.js
  frontend/controller/subscriptionController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerConfirmAccount.scss.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/screens/Influencer/PlanChooseInterface.scss.js
  frontend/screens/Influencer/components/AddHandle.scss.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/Influencer/components/MaxFollowers.scss.js
  frontend/screens/Influencer/components/MaxFollowersNo.js
  frontend/screens/Influencer/components/PricePerPost.js
  frontend/screens/Influencer/components/PricePerPost.scss.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/Influencer/components/UserProfilePhoto.scss.js
  frontend/screens/InfluencerRegistrationForm.js
  frontend/screens/PlanChooseInterface.js
  frontend/screens/signup/components/HeadingDescToggle.jsx
  frontend/screens/signup/components/InfluPrice.jsx
  frontend/shared/PlansBox.jsx
  frontend/util/subscriptionDate.js
Labels: gssoc, level3

#72 Creating a connect request api at backend added
  backend/controllers/connectController.js
  backend/index.js
  backend/model/Message.js
  backend/model/Request.js
  backend/model/brandDbRequestModel.js
  backend/model/influencerSignupRequestModel.js
  backend/routes/connectionRoutes.js
Labels: gssoc, level2

#75 [Frontend] Adding alert notifications Addded
  backend/controllers/brandController.js
  frontend/App.js
  frontend/controller/signupController.js
  frontend/controller/socialController.js
  frontend/controller/subscriptionController.js
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/screens/OtpVerification.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/shared/CustomAlert.jsx
  frontend/util/AlertContext.js
Labels: gssoc, level2

#84 [Backend] Changing Brands and influencer db schema so that profile photo can be saved in db for both Added
  backend/controllers/brandController.js
  backend/controllers/influencerController.js
  backend/index.js
  backend/middleware/brands/validations/brandSignUpValidate.js
  backend/model/brandDbRequestModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/brandRoutes.js
  backend/routes/influencerRoutes.js
  frontend/App.js
  frontend/controller/signupController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/Influencer/components/MaxFollowersNo.js
  frontend/screens/Influencer/components/PricePerPost.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/Influencer/components/UserProfilePhoto.scss.js
Labels: gssoc, level3

#87 [FrontEnd] preview page show hide and refactor preview Fixed
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandAccountSignupDataPreview.js
  frontend/screens/BrandAccountSignupDataPreview.scss.js
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/Influencer/InfluencerConfirmAccount.scss.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/login/LoginStyle.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/screens/signup/SignUpStyles.scss.js
  frontend/util/imagePickerUtil.js
Labels: gssoc, level2

#92 [Frontend] Integration of API for keeping track of collaborations with brandprofile page and making page responsive fixed
  backend/controllers/brandController.js
  backend/middleware/brands/brandAuthenticationMiddleware.js
  backend/routes/collaborationRoutes.js
  frontend/controller/collabrationController.js
  frontend/controller/loginController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandProfile.js
  frontend/screens/BrandProfile.scss.js
Labels: gssoc, level3

#95 [Frontend] Integration Get Profile Page for Brand fixed
  backend/controllers/brandController.js
  backend/routes/brandRoutes.js
  frontend/controller/brandController.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandProfile.scss.js
Labels: gssoc, level2

#98 [Frontend] Back button ui consistency fixes
  frontend/components/Depth1Frame11.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandProfile.scss.js
  frontend/screens/BrandorInfluencer.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/InfluencerRegstrationForm.scss.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/login/LoginStyle.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/screens/signup/SignUpStyles.scss.js
Labels: gssoc, level1

#99 [Backend] Create Missing Brand APIs Added
  backend/controllers/brandController.js
  backend/package-lock.json
  backend/package.json
  backend/routes/brandRoutes.js
Labels: gssoc, level3

#102 [Bug] Profile Picture Not Getting Saved and Login Again & again fixed.
  frontend/App.js
  frontend/controller/collabrationController.js
  frontend/controller/signupController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/BrandProfile.js
  frontend/screens/Homepage.js
  frontend/screens/Influencer/InfluencerRegistrationForm.js
  frontend/screens/Influencer/PlanChooseInterface.js
  frontend/screens/Influencer/components/AddHandles.js
  frontend/screens/Influencer/components/MaxFollowersNo.js
  frontend/screens/Influencer/components/PricePerPost.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
  frontend/screens/OtpVerification.js
  frontend/screens/UserProfile.js
  frontend/screens/signup/BrandRegistrationForm.js
  frontend/shared/MultiSelect.jsx
  frontend/util/imagePickerUtil.js
Labels: gssoc, level3

#122 [Frontend] Add terms of service and privacy policy content to app fixed
  frontend/App.js
  frontend/screens/BrandorInfluencer.js
  frontend/screens/Influencer/InfluencerConfirmAccount.js
  frontend/screens/TosAndPp/PPScreen.js
  frontend/screens/TosAndPp/TosPP.scss.js
  frontend/screens/TosAndPp/TosScreen.js
  frontend/screens/login/LoginPage.js
  frontend/screens/login/LoginPageBrands.js
  frontend/screens/signup/BrandRegistrationForm.js
Labels: gssoc, level1, frontend

#125 [Frontend] Integration of analytics.js with backend completely Added
  frontend/components/Depth1Frame9.js
  frontend/controller/InfluencerController.js
  frontend/controller/loginController.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/Analytics/Analytics.scss.js
  frontend/screens/Influencer/components/UserProfilePhoto.js
Labels: gssoc, level3

#134 [Frontend] Integration of List of influencers api and list of brands api with frontend. Added
  backend/controllers/influencerController.js
  backend/routes/influencerRoutes.js
  frontend/App.js
  frontend/controller/InfluencerController.js
  frontend/controller/brandController.js
  frontend/controller/connectionsController.js
  frontend/screens/BrandProfile.js
  frontend/screens/InfluencerList/IncluencerCard.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/InfluencersList.js
Labels: gssoc, level3

#138 [Backend] link influncers list of each with their respective analytics page and make connect button work completely on analytics page Fixed
  backend/middleware/brandorInfluencerAuthenticationMiddleware.js
  backend/routes/influencerRoutes.js
  frontend/controller/InfluencerController.js
  frontend/controller/socialController.js
  frontend/screens/Analytics/Analytics.js
  frontend/screens/InfluencerList/IncluencerCard.js
  frontend/screens/InfluencerList/InfluencersList.js
Labels: gssoc, level3

#148 Button UI fixed
  frontend/components/BrandProfileBottomBar.js
  frontend/components/Depth1Frame11.js
  frontend/screens/BrandProfile.js
  frontend/screens/BrandsAssosciated.js
  frontend/screens/Homepage.js
  frontend/screens/InfluencerList/InfluencersList.js
  frontend/screens/UserProfile/UserProfile.js
Labels: gssoc, level3
